---
version: '3'
services:

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - /data1/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 5s
      timeout: 20s

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/test-bucket;
      /usr/bin/mc policy set public myminio/test-bucket;
      /usr/bin/mc admin user add myminio flink-sql-runner secretkey;
      /usr/bin/mc admin policy set myminio readwrite user=flink-sql-runner;
      exit 0;
      "

  flink-sql-runner-node:
    build:
      context: ../
      dockerfile: ./docker-compose/flink-sql-runner-node/Dockerfile
      args:
      - FLINK_VERSION=1.15.1
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000

  jobmanager:
    image: flink:1.15.1-scala_2.12-java8
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.15.1.jar
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.access-key: flink-sql-runner
        s3.secret-key: secretkey

  taskmanager:
    image: flink:1.15.1-scala_2.12-java8
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - AWS_ACCESS_KEY_ID=flink-sql-runner
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_S3_ENDPOINT=http://minio:9000
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.15.1.jar
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.access-key: flink-sql-runner
        s3.secret-key: secretkey

volumes:
  minio_storage: {}