---
name: flink-sql-emr-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        pip install -r emr-deployment-scripts/jobs-deployment/requirements.txt -r emr-deployment-scripts/jobs-deployment/tests/requirements.txt

    - name: Analysing the code with black
      run: |
        black --target-version py37 --line-length 120 --check --verbose .

    - name: Test with pytest
      run: |
        pytest
